# Travis CI Configuration File

# Tell Travis CI we're using PHP
language: php

php:
    - 5.3
    - 5.4
    - 5.5
    - 5.6
    - hhvm

script:
    - vendor/bin/phpunit --coverage-clover=coverage.xml

before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction --dev
